export const EnvVars = Object.freeze({
  PORT: "PORT",
  OPENAI_API_KEY: "OPENAI_API_KEY",
  POSTGRES_HOST: "POSTGRES_HOST",
  POSTGRES_PORT: "POSTGRES_PORT",
  POSTGRES_DB: "POSTGRES_DB",
  POSTGRES_USER: "POSTGRES_USER",
  POSTGRES_PASSWORD: "POSTGRES_PASSWORD",
});
